version: '3.7'

services:
  app:
    container_name: chat-websocket-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:3000'
    expose:
      - 80
